### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by Jeff-Lawson** [ProjectVault/orp#2]
It would be great if someone on the Project Vault team could recommend a development board that is capable of loading and running the software!

**Comment by KarolSydor** [comment]
I agree, I found out this project on one of the tech-news site, and It stated that there is some dedicated HW for that. I tried to find some more info it but without any success. It seems that the HW itself can be quite simple, the only thing beside the MCU & some flash is the SD bus with slave support, and some convenient method of connecting it to master system.

**Comment by FUSED-ID** [comment]
Agreed Here as well any HW Reference Board details?

LG Vandenberg

**Comment by daveti** [comment]
Does anyone know the dev board shown in Google’s slides for Vault?

-daveti

**Comment by vladikoff** [comment]
I don't think that board is ready yet, was it coming out in Q3 or Q4?

**Comment by MichalMisiaszek** [comment]
I looked for various Xilinx boards and Geophyte is referenced only in this project.

**Comment by ProjectVault** [comment]
For hardware there's a few choices:
- At Google I/O, we showed demos running on a custom board (the "Geophyte"). We'll be posting the board designs Real Soon Now as open-source hardware.
- If you're looking for something off-the-shelf, the [Digilent Nexys 4](http://www.digilentinc.com/Products/Detail.cfm?Prod=NEXYS4) has the same FPGA as the Geophyte but more peripheral headers and other features. The general purpose IO (GPIO) pins are mapped differently, though, and unfortunately I don't have an alternative UCF file (see [geophyte.ucf](https://github.com/ProjectVault/orp/blob/master/hardware/mselSoC/src/systems/geophyte/data/geophyte.ucf)) on hand. It should not be difficult to adjust the constraints as needed, if you are familiar with such matters.

Sorry I don't have an easier answer!

**Comment by Jeff-Lawson** [comment]
ProjectVault, thanks for taking the time to respond, it's much appreciated  :-)

I shall check out the Nexys 4 board.
