### ISSUE TITLE
Missing QEMU tool

### ISSUE THREAD

**Issue by carmelon** [ProjectVault/orp#3]
Hi,
I'm trying to build the platform and it fails when trying configure qemu-orp. 
Can you please share a link to the qemu-orp project?

Thanks,
Ori

**Comment by MichalMisiaszek** [comment]
What tools are you using to build it ? What HW you want to deploy it on ?
Thanks

**Comment by carmelon** [comment]
I just followied the readme files inside the project to build it.
The HW is not relevant at the moment, that's why I need the QEMU.

**Comment by ProjectVault** [comment]
I've added [qemu-orp](https://github.com/ProjectVault/orp/tree/master/third-party/qemu-orp) to the repository. It contains a README.md with build and usage instructions. Thank you for your patience and please let me know how it works!

**Comment by carmelon** [comment]
The tools and OS were built successfully after this update, thanks!
